"""Review table

Revision ID: 965bf5b0fd58
Revises: 5a078bced901
Create Date: 2024-04-10 15:11:12.016327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965bf5b0fd58'
down_revision = '5a078bced901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
